const AI_PHRASES = [
  "believing in something",
  "bidding dips",
  "avoiding fud",
  "auramaxxing",
  "when it hits",
  "auralius maximus",
  "chadding",
  "looks maxxing",
  "aura.",
  "aura is forever",
  "aura is inevitable",
  "seeing the vision",
  "sniping the dip",
  "skibidi rizz",
  "gigalonging",
  "entering the flow state",
  "auramaxxxxing",
  "working for your bags",
  "understanding lore",
  "lore maxxing",
  "supporting your bro",
  "being a day 1",
  "thinking for yourself",
  "auraaaaaaaa"
  // "Aura basic star",
  // "100% Aura Energy",
  // "A Disco Aura",
  // "Absolute Aura",
  // "Absolute Aura!",
  // "Abundant Aura",
  // "Achieving Aura",
  // "Added Aura!",
  // "Ain't no Aura high enough",
  // "All Hail Aura",
  // "All about that Aura",
  // "All for Aura!",
  // "All in on Aura",
  // "All stormy Aura!",
  // "All-in Aura",
  // "Almost Aura!",
  // "Ancestral Aura",
  // "Angel Aura",
  // "Apex Aura!",
  // "Appreciated Aura",
  // "Ardent Aura ",
  // "Aristocrat Aura",
  // "Ascend to Aura",
  // "Ascendant Aura",
  // "Ascending Aura",
  // "AstralAura!",
  // "Aura 2025!",
  // "Aura Above All",
  // "Aura Ace",
  // "Aura Ace!",
  // "Aura Addict Here",
  // "Aura Addict!",
  // "Aura Addiction",
  // "Aura Admirer",
  // "Aura Adoration",
  // "Aura Adventure",
  // "Aura Age!",
  // "Aura All Day",
  // "Aura Allure",
  // "Aura Anthem",
  // "Aura Army Assembled!",
  // "Aura Array ",
  // "Aura Ascending",
  // "Aura Astral",
  // "Aura Award",
  // "Aura Beacon",
  // "Aura Bedtime",
  // "Aura Believe!",
  // "Aura Beyond",
  // "Aura Blaze",
  // "Aura Blessed",
  // "Aura Bliss",
  // "Aura Bliss!",
  // "Aura Bonfire",
  // "Aura Book",
  // "Aura Boundaries",
  // "Aura Boundless",
  // "Aura Brew!",
  // "Aura Brilliance",
  // "Aura Brilliancy",
  // "Aura Bringer",
  // "Aura Burst",
  // "Aura Calendar",
  // "Aura Calls",
  // "Aura Carnival",
  // "Aura Catalyst",
  // "Aura Champion",
  // "Aura Champions!",
  // "Aura Charged!",
  // "Aura Chaser",
  // "Aura Circuit!",
  // "Aura Circulation!",
  // "Aura Claim",
  // "Aura Cloud ",
  // "Aura Comfort Zone",
  // "Aura Consistency!",
  // "Aura Constant",
  // "Aura Crafted",
  // "Aura Creation.",
  // "Aura Crescendo",
  // "Aura Crest!",
  // "Aura Crew!",
  // "Aura Crusade!",
  // "Aura Crusader",
  // "Aura Cycle",
  // "Aura Dance",
  // "Aura Day",
  // "Aura Dayz!",
  // "Aura Delight",
  // "Aura Delight!",
  // "Aura Diary",
  // "Aura Dice",
  // "Aura Disruption",
  // "Aura Divinity",
  // "Aura Dream!",
  // "Aura Dreamer!",
  // "Aura Dreaming",
  // "Aura Elevation ",
  // "Aura Elysium",
  // "Aura Ember",
  // "Aura Embrace!",
  // "Aura Empire",
  // "Aura Energy!",
  // "Aura Engaged!",
  // "Aura Enhancement",
  // "Aura Enigma",
  // "Aura Enjoyment",
  // "Aura Enthused!",
  // "Aura Enthusiast",
  // "Aura Equinox",
  // "Aura Essence",
  // "Aura Euphoria",
  // "Aura Euphoria!",
  // "Aura Every Minute",
  // "Aura Everything",
  // "Aura Everywhere",
  // "Aura Excellence",
  // "Aura Expands",
  // "Aura Expectation",
  // "Aura Explode",
  // "Aura Explorer",
  // "Aura Fairy",
  // "Aura Fairy!",
  // "Aura Famous!",
  // "Aura Fantasy",
  // "Aura Fantasy!",
  // "Aura Festivity",
  // "Aura Fever",
  // "Aura Fever!",
  // "Aura Fidelity ",
  // "Aura Fighter!",
  // "Aura Firework",
  // "Aura Flame",
  // "Aura Flash",
  // "Aura Flight",
  // "Aura Flux",
  // "Aura Foresight",
  // "Aura Forever",
  // "Aura Forever!",
  // "Aura Fortunes",
  // "Aura Forward!",
  // "Aura Foundry ",
  // "Aura Furnace",
  // "Aura Fusion ",
  // "Aura Future",
  // "Aura Future!",
  // "Aura FutureProof!",
  // "Aura Galaxy",
  // "Aura Galaxy!",
  // "Aura Game Strong",
  // "Aura Generations",
  // "Aura Genesis",
  // "Aura Giant",
  // "Aura Gift!",
  // "Aura Glee",
  // "Aura Glimmer",
  // "Aura Glistens",
  // "Aura Glitz",
  // "Aura Glory",
  // "Aura Glow",
  // "Aura Glow Up",
  // "Aura Gravity",
  // "Aura Gremlin",
  // "Aura Groove",
  // "Aura Guard",
  // "Aura Guard!",
  // "Aura Guru",
  // "Aura Guru!",
  // "Aura Habeas",
  // "Aura Harmony",
  // "Aura Haven",
  // "Aura Heights",
  // "Aura Heights!",
  // "Aura Heritage ",
  // "Aura Hero",
  // "Aura History",
  // "Aura Honor",
  // "Aura Hope!",
  // "Aura Horizon",
  // "Aura Hype",
  // "Aura Illusion",
  // "Aura Imaginative!",
  // "Aura Impulse",
  // "Aura In My Veins",
  // "Aura Incendiary",
  // "Aura Inception!",
  // "Aura Indulged",
  // "Aura Inferno",
  // "Aura Infinite",
  // "Aura Infinity!",
  // "Aura Influence ",
  // "Aura Innate",
  // "Aura Insider",
  // "Aura Instinct",
  // "Aura Investor",
  // "Aura Is Life",
  // "Aura Is My Jam",
  // "Aura IsHere!",
  // "Aura Jeans",
  // "Aura Jewels",
  // "Aura Jog!",
  // "Aura Journey",
  // "Aura Joy!",
  // "Aura Keeper!",
  // "Aura Kernel",
  // "Aura King",
  // "Aura King cool",
  // "Aura Kingdom Awaits",
  // "Aura Kite",
  // "Aura Knock!",
  // "Aura Lead!",
  // "Aura Legacy",
  // "Aura Legacy!",
  // "Aura Legend",
  // "Aura Legends",
  // "Aura Legends!",
  // "Aura Life Chose Me",
  // "Aura Life Goals",
  // "Aura Lift!",
  // "Aura Loom",
  // "Aura Lover",
  // "Aura Lover!",
  // "Aura Luck, All Day",
  // "Aura Lust",
  // "Aura Magic",
  // "Aura Magical!",
  // "Aura Magnet",
  // "Aura Majesty",
  // "Aura Manifest",
  // "Aura Manifestation",
  // "Aura March",
  // "Aura Mark",
  // "Aura Master!",
  // "Aura Mastery",
  // "Aura Mastery!",
  // "Aura Matrix",
  // "Aura Maven",
  // "Aura Meister",
  // "Aura Memorial",
  // "Aura Mindset",
  // "Aura Mode: Activated",
  // "Aura Muse",
  // "Aura Navigator",
  // "Aura Nebula",
  // "Aura Next!",
  // "Aura Nomad",
  // "Aura Non-stop!",
  // "Aura Oasis",
  // "Aura Obsession",
  // "Aura Ocean!",
  // "Aura On My Mind",
  // "Aura On Repeat",
  // "Aura On The Rise",
  // "Aura Onscreen",
  // "Aura Optics",
  // "Aura Optimist",
  // "Aura Over Everything",
  // "Aura Overflow",
  // "Aura Packed!",
  // "Aura Pact ",
  // "Aura Palace",
  // "Aura Palace!",
  // "Aura Paragon",
  // "Aura Passion",
  // "Aura Path ",
  // "Aura Path!",
  // "Aura Pathfinder",
  // "Aura Pathfinders!",
  // "Aura Peaks!",
  // "Aura Pedigree",
  // "Aura Perks!",
  // "Aura Phenomenon",
  // "Aura Pioneer",
  // "Aura Pirates!",
  // "Aura Playbook",
  // "Aura Plus!",
  // "Aura Positive!",
  // "Aura Premium!",
  // "Aura Prestige",
  // "Aura Pride!",
  // "Aura Prodigal",
  // "Aura Prodigy",
  // "Aura Propulsion ",
  // "Aura Pulse",
  // "Aura Purity",
  // "Aura Pyro",
  // "Aura Quest",
  // "Aura Quester",
  // "Aura Radiance",
  // "Aura Raiders",
  // "Aura Realm",
  // "Aura Rebirth ",
  // "Aura Recipe",
  // "Aura Reflections ",
  // "Aura Reign",
  // "Aura Reign!",
  // "Aura Relentless!",
  // "Aura Returns!",
  // "Aura Revelation",
  // "Aura Revolution",
  // "Aura Rhythm!",
  // "Aura Rides!",
  // "Aura Road Trip",
  // "Aura Roadmap",
  // "Aura Roamer",
  // "Aura Rocket",
  // "Aura Royal",
  // "Aura Ruler",
  // "Aura Ruler!",
  // "Aura Rules Everything",
  // "Aura Rush!",
  // "Aura Sauce",
  // "Aura Score!",
  // "Aura Seek",
  // "Aura Seeker",
  // "Aura Sensation",
  // "Aura Sensation ",
  // "Aura Shaft!",
  // "Aura Shaper",
  // "Aura Signal!",
  // "Aura Sing",
  // "Aura Skies",
  // "Aura Sky High",
  // "Aura Skylines",
  // "Aura Sparkle",
  // "Aura Spectacular",
  // "Aura Sphere",
  // "Aura Sphere!",
  // "Aura Splendor",
  // "Aura Sprint",
  // "Aura Squad Unite",
  // "Aura Stability",
  // "Aura Star",
  // "Aura Stargazer",
  // "Aura Starlit",
  // "Aura States!",
  // "Aura Station!",
  // "Aura Stature ",
  // "Aura Steps Ahead",
  // "Aura Stratosphere",
  // "Aura Strength",
  // "Aura Success Story",
  // "Aura Summit!",
  // "Aura Sunset",
  // "Aura Super!",
  // "Aura Supernova",
  // "Aura Supremacy!",
  // "Aura Surge",
  // "Aura Swag",
  // "Aura Symphony",
  // "Aura Tapestry",
  // "Aura Temple!",
  // "Aura Thermo",
  // "Aura Thrills!",
  // "Aura Thriving",
  // "Aura Tidal Wave!",
  // "Aura Times",
  // "Aura Titan",
  // "Aura Torch",
  // "Aura Tradition",
  // "Aura Trail!",
  // "Aura Trailblazer",
  // "Aura Traverse",
  // "Aura Treasure",
  // "Aura Tribute",
  // "Aura Triumph!",
  // "Aura Triumphs",
  // "Aura Trooper",
  // "Aura Tumult",
  // "Aura Twinkle",
  // "Aura Ultra!",
  // "Aura Unison",
  // "Aura United ",
  // "Aura Universe",
  // "Aura Up, Never Down",
  // "Aura Upgrade",
  // "Aura Valor",
  // "Aura Venture",
  // "Aura Vibes Only",
  // "Aura Vibing!",
  // "Aura Victory",
  // "Aura Vision",
  // "Aura Voila!",
  // "Aura Vortex",
  // "Aura Voyage",
  // "Aura Wave",
  // "Aura Waves!",
  // "Aura Wellness",
  // "Aura Whisper ",
  // "Aura Whisperer",
  // "Aura Whispers",
  // "Aura Whiz",
  // "Aura Winners!",
  // "Aura Winning",
  // "Aura Winning Streak",
  // "Aura Wonder",
  // "Aura World!",
  // "Aura XYZ!",
  // "Aura Xtreme! ",
  // "Aura Zeal",
  // "Aura Zenith",
  // "Aura accel",
  // "Aura ace",
  // "Aura action",
  // "Aura adventure!",
  // "Aura affair",
  // "Aura agenda!",
  // "Aura all rounder!",
  // "Aura ambition",
  // "Aura and Beyond",
  // "Aura and Chill",
  // "Aura and Everything!",
  // "Aura and I",
  // "Aura and love",
  // "Aura awesome",
  // "Aura awkard",
  // "Aura basics",
  // "Aura beast",
  // "Aura beast mode",
  // "Aura beats!",
  // "Aura beliefs!",
  // "Aura believer",
  // "Aura belongings!",
  // "Aura blessed",
  // "Aura bliss",
  // "Aura bloom",
  // "Aura bold",
  // "Aura boost",
  // "Aura boss",
  // "Aura bounce ",
  // "Aura boundless",
  // "Aura breakthrough",
  // "Aura breakthrough!",
  // "Aura brightness",
  // "Aura camp",
  // "Aura certainties",
  // "Aura champ",
  // "Aura charitable deeds!",
  // "Aura charm",
  // "Aura cheer",
  // "Aura chiefs!",
  // "Aura children's delight!",
  // "Aura circle",
  // "Aura class",
  // "Aura closeness!",
  // "Aura co existence!",
  // "Aura construction!",
  // "Aura cool",
  // "Aura core firmness!",
  // "Aura craze",
  // "Aura creatives!",
  // "Aura dance",
  // "Aura dash",
  // "Aura dayz ",
  // "Aura decisions arrived!",
  // "Aura dee",
  // "Aura delight seekers!",
  // "Aura delight!",
  // "Aura delightful",
  // "Aura deluxe",
  // "Aura discovery!",
  // "Aura dreamer",
  // "Aura dreams",
  // "Aura elite",
  // "Aura empire",
  // "Aura enthusiasm!",
  // "Aura enthusiasts!",
  // "Aura epic",
  // "Aura essence",
  // "Aura essential",
  // "Aura essential checks!",
  // "Aura eternal vibes!",
  // "Aura exhibit",
  // "Aura exploration!",
  // "Aura explosion",
  // "Aura express",
  // "Aura fairness!",
  // "Aura fantasy!",
  // "Aura feisty",
  // "Aura fest",
  // "Aura fever",
  // "Aura fever ",
  // "Aura fever!",
  // "Aura fiesta",
  // "Aura fire",
  // "Aura firm",
  // "Aura flames!",
  // "Aura flash",
  // "Aura flex",
  // "Aura focused!",
  // "Aura fondness",
  // "Aura for Life",
  // "Aura founders!",
  // "Aura frenzy",
  // "Aura fresh",
  // "Aura friendly",
  // "Aura frontier",
  // "Aura fun",
  // "Aura fun factory",
  // "Aura fusion",
  // "Aura galaxy size",
  // "Aura genius",
  // "Aura gifts",
  // "Aura glitz",
  // "Aura glorify",
  // "Aura glory goals",
  // "Aura glory trees!",
  // "Aura glow",
  // "Aura glow-up",
  // "Aura goal!",
  // "Aura going high!",
  // "Aura golden!",
  // "Aura grand",
  // "Aura great!",
  // "Aura grind",
  // "Aura grounds!",
  // "Aura grow",
  // "Aura happens",
  // "Aura happiness!",
  // "Aura happy",
  // "Aura healthy plans!",
  // "Aura highlights ",
  // "Aura hit!",
  // "Aura hoarding",
  // "Aura holiday plans!",
  // "Aura honest",
  // "Aura hoop life",
  // "Aura hustle",
  // "Aura icon",
  // "Aura ideas",
  // "Aura identity",
  // "Aura immersive",
  // "Aura is golden",
  // "Aura is the future",
  // "Aura journey!",
  // "Aura karma",
  // "Aura king!",
  // "Aura king/queen",
  // "Aura knowledge!",
  // "Aura launch",
  // "Aura leading!",
  // "Aura league",
  // "Aura learnings!",
  // "Aura legacy",
  // "Aura legend",
  // "Aura legendary",
  // "Aura life",
  // "Aura life's good",
  // "Aura lifetime",
  // "Aura lift",
  // "Aura lights!",
  // "Aura lites!",
  // "Aura living essentials!",
  // "Aura love",
  // "Aura luck",
  // "Aura magic",
  // "Aura magic!",
  // "Aura magnet",
  // "Aura manifest",
  // "Aura marathon!",
  // "Aura massive!",
  // "Aura master",
  // "Aura masterclass",
  // "Aura match points!",
  // "Aura mighty!",
  // "Aura mode",
  // "Aura model!",
  // "Aura momentum",
  // "Aura mystique",
  // "Aura nature seeker!",
  // "Aura navigation!",
  // "Aura negotiations!",
  // "Aura network!",
  // "Aura neutralised!",
  // "Aura of Worship",
  // "Aura on peak",
  // "Aura on top!",
  // "Aura onfire",
  // "Aura party",
  // "Aura path to wealth!",
  // "Aura paths of blessings!",
  // "Aura peak",
  // "Aura peers",
  // "Aura perfect goals!",
  // "Aura perfect!",
  // "Aura perfection!",
  // "Aura phenomenal!",
  // "Aura phenomenon!",
  // "Aura phoenix",
  // "Aura pioneer",
  // "Aura planting goals!",
  // "Aura pop",
  // "Aura positivity forever!",
  // "Aura power",
  // "Aura prayers!",
  // "Aura pride",
  // "Aura pride!",
  // "Aura pro",
  // "Aura prosperity",
  // "Aura queen/king",
  // "Aura quest",
  // "Aura quest!",
  // "Aura radar!",
  // "Aura rain",
  // "Aura rand!",
  // "Aura rays",
  // "Aura realm",
  // "Aura reforms!",
  // "Aura reign",
  // "Aura relatives!",
  // "Aura resources!",
  // "Aura resumption!",
  // "Aura revamping!",
  // "Aura rich history!",
  // "Aura ride",
  // "Aura rise",
  // "Aura rock!",
  // "Aura rockz",
  // "Aura roots!",
  // "Aura rule #1: Believe",
  // "Aura rules",
  // "Aura rush",
  // "Aura sanctuary",
  // "Aura sauce",
  // "Aura schedules!",
  // "Aura school",
  // "Aura seen",
  // "Aura sense",
  // "Aura simply!",
  // "Aura skill games!",
  // "Aura space loves!",
  // "Aura spaces!",
  // "Aura spark",
  // "Aura spin",
  // "Aura spiritually!",
  // "Aura spree",
  // "Aura spree!",
  // "Aura star",
  // "Aura stride",
  // "Aura strike",
  // "Aura strong learners!",
  // "Aura stunner",
  // "Aura stunning",
  // "Aura summit",
  // "Aura sunrise!",
  // "Aura sunshine!",
  // "Aura supply needs!",
  // "Aura supports!",
  // "Aura supreme!",
  // "Aura surge",
  // "Aura sweet feeding!",
  // "Aura tear!",
  // "Aura tend",
  // "Aura the Great!",
  // "Aura the King",
  // "Aura the life",
  // "Aura the moon",
  // "Aura the queen",
  // "Aura themed",
  // "Aura thrill",
  // "Aura thunder",
  // "Aura ticks",
  // "Aura timezone!",
  // "Aura to glow",
  // "Aura to the Sky",
  // "Aura to the moon!",
  // "Aura transcending!",
  // "Aura transformation!",
  // "Aura transformations!",
  // "Aura treasure",
  // "Aura trees!",
  // "Aura tribe",
  // "Aura trips!",
  // "Aura ultimate",
  // "Aura ultimate ",
  // "Aura unicorn!",
  // "Aura unlimited",
  // "Aura uplift",
  // "Aura uplifting",
  // "Aura valiant!",
  // "Aura valour!",
  // "Aura venture",
  // "Aura ventures!",
  // "Aura vibe",
  // "Aura vibes",
  // "Aura vibes going strong!",
  // "Aura vibes only",
  // "Aura vibes!",
  // "Aura victory",
  // "Aura viral!",
  // "Aura virtual!",
  // "Aura vision",
  // "Aura warrior",
  // "Aura wave",
  // "Aura whirl",
  // "Aura whisperer",
  // "Aura win!",
  // "Aura wings!",
  // "Aura winner",
  // "Aura wins!",
  // "Aura wish ",
  // "Aura wonder",
  // "Aura world vision!",
  // "Aura zeal",
  // "Aura zealot",
  // "Aura zen",
  // "Aura zinger",
  // "Aura zone",
  // "Aura's Biggest Fan",
  // "Aura-Aura-Aura!",
  // "Aura-Fueled Fun",
  // "Aura-Hungry",
  // "Aura-Nation!",
  // "Aura-O-clock!",
  // "Aura-Pro!",
  // "Aura-Renaissance!",
  // "Aura-Time!",
  // "Aura-Universe!",
  // "Aura-Warrior!",
  // "Aura-abration!",
  // "Aura-ai!",
  // "Aura-blessed",
  // "Aura-champion",
  // "Aura-cious move!",
  // "Aura-elite",
  // "Aura-galaxy",
  // "Aura-goal!",
  // "Aura-heights!",
  // "Aura-hits!",
  // "Aura-infinitely!",
  // "Aura-jacent",
  // "Aura-mania",
  // "Aura-mazing!",
  // "Aura-miracle",
  // "Aura-niverse",
  // "Aura-o-licious!",
  // "Aura-powered!",
  // "Aura-tacular!",
  // "Aura-tastic adventure",
  // "Aura-tide",
  // "Aura-time all the time",
  // "Aura.connection!",
  // "Aura.fly!",
  // "AuraBoss",
  // "AuraCapital!",
  // "AuraDelight!",
  // "AuraFX",
  // "AuraFans!",
  // "AuraFever!",
  // "AuraLife!",
  // "AuraLove",
  // "AuraMyth!",
  // "AuraPeace!",
  // "AuraPlanet!",
  // "AuraPride!",
  // "AuraRev!",
  // "AuraRule!",
  // "AuraScope!",
  // "AuraShine",
  // "Aura_Boost",
  // "Aura_Era",
  // "Aura_dreaming",
  // "Aura_ever",
  // "Aura_gang",
  // "Aura_mistake",
  // "Aura_zesty",
  // "Auralicious",
  // "Auralife fun",
  // "Aurora Borealis? Aura Borealis!",
  // "Aurrific aura ",
  // "Awe of Aura",
  // "AweAura!",
  // "Awesome Aura!",
  // "Basic_Aura",
  // "Be Aura rich",
  // "Be unique Aura!",
  // "Beaming Aura",
  // "Beauty Aura!",
  // "Being Aura-tiful",
  // "Best of Aura!",
  // "Best with Aura",
  // "Better off Aura!   ",
  // "Beyond Aura!",
  // "BeyondAura!",
  // "BeyoundAura!",
  // "Billionaire Aura",
  // "Blessing Aura",
  // "BlissAura!",
  // "Blissful Aura",
  // "BlissfulAura",
  // "Borderless Aura!",
  // "Born With Aura",
  // "Born of Aura",
  // "Bound By Aura ",
  // "Boundless Aura",
  // "Breath of Aura",
  // "Bright Aura",
  // "Bright Aura star ",
  // "Brilliant Aura",
  // "Bubble Of Aura",
  // "Burning Aura",
  // "Catching Aura Waves",
  // "Celebrate Aura",
  // "Celestial Aura",
  // "Certain Aura",
  // "Charmed By Aura",
  // "Chasing Aura Gains",
  // "Cheer In Aura",
  // "Cherished Aura",
  // "Claiming Aura",
  // "Clean-Aura!",
  // "Climbing Aura Peaks",
  // "Confident Aura",
  // "Consistent Aura",
  // "Cool as Aura",
  // "CoreAura!",
  // "Cosmic Aura",
  // "Cosmical Aura!",
  // "Countless Aura",
  // "CraftAura!",
  // "Craving Aura",
  // "Creative Aura!",
  // "Crescent Aura",
  // "Crown of Aura",
  // "Crowned Aura",
  // "Cultural Aura!",
  // "Daily Aura",
  // "Daily Aura dose",
  // "Definite Aura",
  // "Defying Aura",
  // "Dependable Aura",
  // "Destiny with Aura",
  // "Dignified Aura",
  // "Discover Aura",
  // "Divine Aura",
  // "Divine Aura fever",
  // "Divine Aura!",
  // "Doin' Aura",
  // "Drawing Aura",
  // "Dream in Aura",
  // "Dream with Aura!",
  // "DreamAura.Ever!",
  // "Electrifying Aura",
  // "Elevate Aura",
  // "Elevate With Aura",
  // "Elevated Aura",
  // "Elevated Aura!",
  // "Embrace Aura",
  // "Embrace the Aura",
  // "Embracing Aura",
  // "EmpathAura",
  // "Enchanted Aura!",
  // "Endless Aura",
  // "Enjoyable Aura!",
  // "Envision Aura",
  // "Epic Aura",
  // "EraofAura!",
  // "Essence Of Aura",
  // "Essence of Aura",
  // "Esteemed Aura",
  // "Eternal Aura",
  // "Eternity Aura",
  // "Ethereal Aura",
  // "Ethereal Aura!",
  // "Ethical Aura",
  // "Ethical Aura!",
  // "Evoke Aura",
  // "Excel With Aura",
  // "Excess Aura",
  // "Expanded Aura!",
  // "Expanding Aura",
  // "Expansive Aura",
  // "Exquisite Aura!",
  // "Extended Aura!",
  // "Extra-est Aura!",
  // "Fantasy Aura!",
  // "Feel the Aura",
  // "Feelin' Aura",
  // "Feeling Aura-tastic",
  // "Festive Aura!",
  // "Fiery Aura",
  // "Find Aura!",
  // "Flaming Aura",
  // "Fleeting Aura",
  // "FollowMultiAura!",
  // "ForAura!",
  // "Fortune Aura!",
  // "Found Aura",
  // "Free-to-Aura",
  // "Full Throttle Aura",
  // "Full send Aura",
  // "Fullest Aura!",
  // "Funtaura!",
  // "Galactic Aura",
  // "Galactic Aura ",
  // "Galaxy Aura fun",
  // "Get Aura!",
  // "Get Lit Aura!",
  // "Get-in-Aure!",
  // "Gleaming Aura",
  // "Global Aura!",
  // "Globetrotting With Aura",
  // "Glorious Aura",
  // "Glowing Aura",
  // "Go full Aura!",
  // "Go go Aura",
  // "GoAura!",
  // "Goal_Aura!",
  // "Going High Aura!",
  // "Gold Aura",
  // "GoldAura",
  // "Golden Aura",
  // "Good Aura",
  // "Got Aura? Join Me",
  // "Grand Aura",
  // "Grand Aura!",
  // "Great Aura",
  // "HODLAURA!",
  // "HODLing Aura",
  // "Half 'n' Aura!",
  // "Happy Aura",
  // "Happy Aura days!",
  // "Happy Aura!",
  // "HappyAuraing!",
  // "Heated Aura",
  // "Hell Aura!",
  // "Here Comes Aura!",
  // "Heritage Aura",
  // "Heroic Aura!",
  // "Highest Aura",
  // "Highly Aura!",
  // "Hoggy-Aura!",
  // "Honoring Aura",
  // "Honourable Aura",
  // "Horizon Aura",
  // "Hype up Aura",
  // "Hyped About Aura",
  // "HyperAura!",
  // "I Am Aura Rich",
  // "I Earned Aura",
  // "I'm All Aura",
  // "I'm Aura Crazy",
  // "Imbue Aura ",
  // "In Aura We Trust",
  // "In Aura we trust",
  // "Inferno Aura",
  // "Infinite Aura",
  // "Infinite Aura!",
  // "Infinity Aura",
  // "Infinity Aura!",
  // "Infinity in Aura",
  // "International Aura!",
  // "Invincible Aura!",
  // "Inviting Aura",
  // "It's Aura magic!",
  // "It’s Aura",
  // "Join the Aura-lution",
  // "Keep calm and Aura on",
  // "Keeping It Aura",
  // "Keeping it Aura-real",
  // "KingOfAura!",
  // "Kingdom of Aura",
  // "Legendary Aura",
  // "Legendary Aura!",
  // "Let's Aura Up",
  // "Life in Aura",
  // "Life in Aura style",
  // "LightSpeed_Aura!",
  // "Lighted Aura",
  // "Limitless Aura",
  // "Limitless Aura!",
  // "LinearAura",
  // "Lit Aura",
  // "Lit Aura ",
  // "Lit By Aura",
  // "Live 'n' Aura!",
  // "Live, laugh, Aura",
  // "Living Aura",
  // "Living Aura Large",
  // "Living the Aura Dream",
  // "Logical Aura!",
  // "Love Aura",
  // "Love life Aura!",
  // "LoveAura",
  // "Love_Aura_ever!",
  // "Loyalty in Aura! ",
  // "Lucky Aura",
  // "Luminary Aura",
  // "Luminescent Aura",
  // "Luminous Aura",
  // "Magic Aura",
  // "Magnificent Aura",
  // "Majestic Aura",
  // "Major Aura vibes",
  // "Making Aura Moves",
  // "Max Aura",
  // "Maximum Aura",
  // "Me and Aura!",
  // "Mega Aura",
  // "Metamorphosize Aura",
  // "Mind-blowing Aura!",
  // "MindblowingAura",
  // "Minty Aura",
  // "Money Aura ",
  // "More the Aura!",
  // "MostAura!",
  // "My Aura ",
  // "My Aura Journey",
  // "My Aura Quote",
  // "My Aura Ride",
  // "My Daily Aura",
  // "MysticAura!",
  // "Mystical Aura",
  // "Nested Aura",
  // "No stopping Aura",
  // "Noble Aura",
  // "One With Aura",
  // "Only Aura!",
  // "Optimistic Aura",
  // "OraconAura!",
  // "Orbiting Aura",
  // "Overall AuraSky!",
  // "Paradigm Aura ",
  // "Paradise Aura!",
  // "Perfect Aura!",
  // "Perpetual Aura",
  // "Persistent Aura",
  // "Phenomenal Aura",
  // "Pioneering Aura",
  // "Pivotal Aura",
  // "Playin' With Aura",
  // "Plus Aura!",
  // "Portal of Aura!",
  // "Positive Aura",
  // "Possess Aura",
  // "Powered By Aura",
  // "Prism Aura",
  // "Prismatic Aura!",
  // "Pristine Aura!",
  // "Prize Aura",
  // "Pro-Aura!",
  // "Progeny Aura",
  // "Promised Aura",
  // "Proud Aura",
  // "Pure Aura",
  // "Pure Aura Light",
  // "Pure Aura Power",
  // "PureAura",
  // "Purely Aura!",
  // "Purest Aura!",
  // "Purest_Aura",
  // "Quantum Aura",
  // "Radiant Aura",
  // "Real Aura",
  // "Reaping Aura Rewards",
  // "Regal Aura",
  // "Reliable Aura",
  // "Remembered Aura",
  // "Respected Aura",
  // "Resplendent Aura",
  // "Returning Aura",
  // "Revel in Aura",
  // "Revered Aura",
  // "Reverence Aura!",
  // "Riding Aura Waves",
  // "Riding the Aura wave",
  // "Riot of Aura",
  // "Roaring Aura",
  // "Royally Aura",
  // "Rush of Aura",
  // "Safe Aura!",
  // "Sail With Aura",
  // "Secret Of Aura",
  // "Seeking Aura",
  // "Seeking Aura ",
  // "Seeking Aura Bliss",
  // "Seeking Aura Thrills",
  // "Serenity of Aura",
  // "Sestinas of Aura",
  // "Shaping Aura",
  // "Shimmering Aura",
  // "Shine Aura",
  // "Shine With Aura",
  // "Shining Aura",
  // "ShiningAura!",
  // "Shiny Aura",
  // "Sky's the limit, Aura!",
  // "So Aura!",
  // "Soar Aura",
  // "Soarin' With Aura",
  // "Soaring Aura",
  // "Solid Aura",
  // "Soul of Aura",
  // "Space Aura!",
  // "Sparkle Aura!",
  // "Sparkling Aura",
  // "Spin With Aura",
  // "Splendid Aura",
  // "Spotlight On Aura",
  // "Spread Aura!",
  // "Spreading Aura Everywhere",
  // "Spreading Aura Joy",
  // "Stay Aura",
  // "Stay Aura fest",
  // "Stay Aura happy",
  // "Stay happy Aura!",
  // "Stay lucky Aura",
  // "Steady Aura!",
  // "Stellar Aura",
  // "Sterling Aura",
  // "Still Aura!",
  // "Strong Aura",
  // "Sum_Aura",
  // "SummerAura",
  // "Super Aura",
  // "Supercool_Aura",
  // "Superior Aura",
  // "Supernatural_Aura!",
  // "Supreme Aura",
  // "Sure Aura",
  // "Sustaining Aura",
  // "Sweet Aura",
  // "Swift Aura",
  // "SynchAure!",
  // "Tender Aura",
  // "That Aura energy",
  // "That bright Aura!",
  // "The Aura Chase!",
  // "The Aura Effect",
  // "The Aura Fly!",
  // "The Aura Mantra!",
  // "The Aura Show!",
  // "The Aura Source!",
  // "The Aura Times!",
  // "The Aura Uprising!",
  // "The Aura Wave!",
  // "The Aura effect",
  // "The Aura way",
  // "The Aura-Era!",
  // "The Power of Aura",
  // "Thriving Aura",
  // "Time-Honored Aura",
  // "Timeless Aura",
  // "Times of Aura",
  // "Toast to Aura",
  // "Top Aura!",
  // "TopAura!",
  // "Totally Aura-fied",
  // "Trail of Aura",
  // "Tranquil Aura",
  // "Treasure Aura",
  // "Treasure Aura ",
  // "Treasured Aura",
  // "True Aura",
  // "True Aura Seeker",
  // "True Aura mate",
  // "Trusted Aura",
  // "Trustworthy Aura",
  // "Ultimate Aura ",
  // "Ultimate_Aura",
  // "Unbounded Aura",
  // "Unique Aura!",
  // "Unstoppable Aura",
  // "Upgrade-Aura!",
  // "Upgraded Aura!",
  // "Uplift With Aura",
  // "Valued Aura",
  // "Vast Aura",
  // "Venerated Aura",
  // "Vibrant Aura",
  // "Viral Aura!",
  // "Vision of Aura",
  // "Visionary Aura",
  // "Vivid Aura",
  // "VividAura!",
  // "Vortex of Aura",
  // "Wake Up, Aura!",
  // "Walk with Aura",
  // "Welcome to Aura!",
  // "Welcoming Aura!",
  // "Well Aura",
  // "What's AURA!",
  // "Why Aura!",
  // "Wild Aura Ride",
  // "Will of Aura",
  // "Winning Aura ",
  // "Wonderful Aura",
  // "Write My Aura",
  // "Yesss Aura",
  // "Yin&Yang Aura!",
  // "You got the Aura",
  // "Zap! Aura"
];



module.exports = AI_PHRASES;
